#cloud-config
runcmd:
  - |
    # Retrieve token and hash from GCP Secret Manager
    SECRET=$(gcloud secrets versions access latest --secret="${k8s-secret}")
    TOKEN=$(echo "$SECRET" | cut -d':' -f1)
    HASH=$(echo "$SECRET" | cut -d':' -f2)

    # Join the Kubernetes cluster (replace <MASTER_IP>)
    kubeadm join <MASTER_IP>:6443 --token $TOKEN --discovery-token-ca-cert-hash sha256:$HASH
