name: Build OS Images for Testing Environment

on:
  push:
    branches:
      - 'feature/**' 
    paths:
      - 'packer/**'

jobs:
  filter-images:
    runs-on: ubuntu-22.04 
    outputs:
      k8s_node: ${{ steps.filter-images.outputs.k8s_node }}
      load_balancer: ${{ steps.filter-images.outputs.load_balancer }}
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: dorny/paths-filter@v2
        id: filter-images
        with:
          filters: |
            k8s_node:
              - 'packer/images/k8s-node/**'
              - 'packer/shared-scripts/**'
            load_balancer:
              - 'packer/images/load-balancer/**'
              - 'packer/shared-scripts/**'

  k8s_node:
    needs: filter-images
    if: needs.filter-images.outputs.k8s_node == 'true'
    uses: ./.github/workflows/build-image.yml
    with:
      environment: testing
      project: gcloud-infra-testing-aab1735b 
      github-runner: ubuntu-22.04
      packer-version: 1.12.0 
      working-directory: packer/images/k8s-node
      build-version: build${{ github.run_number }}
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
  load_balancer:
    needs: filter-images
    if: needs.filter-images.outputs.load_balancer == 'true'
    uses: ./.github/workflows/build-image.yml
    with:
      environment: testing
      project: gcloud-infra-testing-aab1735b 
      github-runner: ubuntu-22.04
      packer-version: 1.12.0 
      working-directory: packer/images/load-balancer
      build-version: build${{ github.run_number }}
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
