name: Deprovision obsolete infra components

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'testing'
        type: choice
        options:
          - testing

jobs:
  deprovision_testing:
    if: ${{ github.event.inputs.environment == 'testing' }}
    uses: ./.github/workflows/update-terraform-vars.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      project: gcloud-infra-testing-aab1735b
      github-runner: ubuntu-22.04
      action: deprovision_infra
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
      CICD_TOKEN: ${{ secrets.CICD_TOKEN }}
