name: Post Release 
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  filter_envs:
    if: > 
      github.event.pull_request.merged == true
      && startsWith(github.event.pull_request.head.ref, 'releases/rollout')
    runs-on: ubuntu-22.04
    outputs:
      testing: ${{ steps.filter.outputs.testing }}
      prod: ${{ steps.filter.outputs.prod }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Filter envs with changes
        id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            testing:
              - 'releases/release-manifest.testing.json'
            prod:
              - 'releases/release-manifest.prod.json'

  testing:
    needs: filter_envs
    if: needs.filter_envs.outputs.testing == 'true'
    uses: ./.github/workflows/release.yml
    with:
      action: POST
      environment: testing
      github-runner: ubuntu-22.04
    secrets:
      CICD_TOKEN: ${{ secrets.CICD_TOKEN }}
