name: Post Release Operations
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  filter_envs:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'releases/')
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Filter envs with changes
        id: filter_envs
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            testing:
              - 'releases/release-manifest.testing.json'
            prod:
              - 'releases/release-manifest.prod.json'

      - name: Build matrix based on changed envs
        id: set-matrix
        run: |
          MATRIX=()
          if [[ "${{ steps.filter-envs.outputs.testing }}" == "true" ]]; then
            MATRIX+=('{"env":"testing","project":"gcloud-infra-testing-aab1735b"}')
          fi
          if [[ "${{ steps.filter-envs.outputs.prod }}" == "true" ]]; then
            MATRIX+=('{"env":"prod","tfvars":"prod.tfvars.json","project":"prod-project"}')
          fi
          echo "matrix=$(jq -n --argjson m "[${MATRIX[*]}]" '$m')" >> $GITHUB_OUTPUT

  promote_infra:
    needs: filter_envs
    if: needs.filter_envs.outputs.matrix != '[]' 
    uses: ./.github/workflows/promote-infra.yml
    with:
      environment: testing
      github-runner: ubuntu-22.04
    secrets:
      CICD_TOKEN: ${{ secrets.CICD_TOKEN }}
