name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'testing'
        type: choice
        options:
          - prod
          - testing
      version:
        description: 'Enter the version for the release'
        required: true
        default: '0.0.1'
        type: string
    secrets:
      GOOGLE_CREDENTIALS_B64:
        required: true
      CICD_TOKEN:
        required: false

jobs:
  prepare:
    uses: ./.github/workflows/release.yml
    with:
      action: PREPARE 
      environment: ${{ inputs.environment }}
      release: ${{ inputs.environment == 'prod' && inputs.version || inputs.version-inputs.environment }} 
      github-runner: ubuntu-22.04
      release_manifest: releases/release-manifest.${{ inputs.environment }}.json
    secrets:
      CICD_TOKEN: ${{ secrets.CICD_TOKEN }}
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
