name: Provision Components 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  filter_components:
    runs-on: ${{ inputs.github-runner }} 
    outputs:
      project: ${{ steps.filter.outputs.project }}
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            kubernetes:
              - 'testing/kubernetes/**'

  project:
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: ${{ inputs.environment }}
      working-directory: testing/project
      tf-state-prefix: project
  kubernetes:
    needs: [filter_components, project]
    if: ${{ needs.filter_components.outputs.kubernetes == 'true' }} 
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: ${{ inputs.environment }}
      tf-state: ${{ inputs.project }}-k8s-green-tf-state
      working-directory: terraform/k8s
      vars: green.tfvars.json
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
