name: Provision Testing Environment

on:
  push:
    branches:
      - 'feature/**'
      - 'auto/**'
      - 'main'
    paths:
      - 'terraform/**'

jobs:
  filter-components:
    runs-on: ubuntu-22.04
    outputs:
      project: ${{ steps.filter-components.outputs.project }}
      network: ${{ steps.filter-components.outputs.network }}
      k8s_blue: ${{ steps.filter-components.outputs.k8s_blue }}
      k8s_green: ${{ steps.filter-components.outputs.k8s_green }}
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: dorny/paths-filter@v3.0.2
        id: filter-components
        with:
          filters: |
            project:
              - 'terraform/project/**'
            network:
              - 'terraform/network/**'
            k8s_green:
              - 'terraform/k8s/**/green.tfvars.json'
            k8s_blue:
              - 'terraform/k8s/**/blue.tfvars.json'

  project:
    needs: filter-components
    if: needs.filter-components.outputs.project == 'true' 
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: testing
      working-directory: terraform/project
      terraform-version: 1.11.4
      github-runner: ubuntu-22.04
      tf-state: gcloud-infra-testing-aab1735b-project-tf-state
      vars: testing.tfvars.json
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
      BILLING_ACCOUNT_ID: ${{ secrets.BILLING_ACCOUNT_ID }}
  network:
    needs: [filter-components, project]
    if: ${{ ! failure() && ! cancelled() && needs.filter-components.outputs.network == 'true' }} 
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: testing
      working-directory: terraform/network
      terraform-version: 1.11.4
      github-runner: ubuntu-22.04
      tf-state: gcloud-infra-testing-aab1735b-network-tf-state
      vars: testing.tfvars.json
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
  k8s_blue:
    needs: [filter-components, project, network]
    if: ${{ ! failure() && ! cancelled() && needs.filter-components.outputs.k8s_blue == 'true' }} 
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: testing
      working-directory: terraform//k8s
      terraform-version: 1.11.4
      github-runner: ubuntu-22.04
      tf-state: gcloud-infra-testing-aab1735b-k8s-blue-tf-state
      vars: blue.tfvars.json
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
  k8s_green:
    needs: [filter-components, project, network]
    if: ${{ ! failure() && ! cancelled() && needs.filter-components.outputs.k8s_green == 'true' }} 
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: testing
      working-directory: terraform/k8s
      terraform-version: 1.11.4
      github-runner: ubuntu-22.04
      tf-state: gcloud-infra-testing-aab1735b-k8s-green-tf-state
      vars: green.tfvars.json
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
