name: Provision Testing Environment

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'testing/**'

permissions:
  id-token: write
  contents: read

jobs:
  filter_components:
    runs-on: ubuntu-22.04
    outputs:
      release: ${{ steps.read_release.outputs.release }}
      project: ${{ steps.filter.outputs.project }}
      network: ${{ steps.filter.outputs.network }}
      kubernetes: ${{ steps.filter.outputs.kubernetes }}
    steps:
      - uses: actions/checkout@v4.2.2

      - id: read_release
        name: Read release version from release manifest
        run: |
          VERSION=$(jq -r '.version' releases/release-manifest.testing.json)
          echo "Release version: $VERSION"
          echo "release=v$VERSION" >> $GITHUB_OUTPUT

      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            project:
              - 'testing/project/**'
            network:
              - 'testing/network/**'
            kubernetes:
              - 'testing/kubernetes/**'

  project:
    needs: filter_components
    if: ${{ needs.filter_components.outputs.project == 'true' }} 
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: testing 
      working-directory: testing/project
      tf-state-prefix: project
    secrets: inherit
  network:
    needs: [filter_components, project]
    if: ${{ ! failure() && ! cancelled() && needs.filter_components.outputs.network == 'true' }}
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: testing
      working-directory: testing/network
      tf-state-prefix: network
    secrets: inherit
  kubernetes:
    needs: [filter_components, project, network]
    if: ${{ ! failure() && ! cancelled() && needs.filter_components.outputs.kubernetes == 'true' }} 
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: testing 
      working-directory: testing/kubernetes
      tf-state-prefix: kubernetes/${{ needs.filter_components.outputs.release }}
      release: ${{ needs.filter_components.outputs.release }}
    secrets: inherit
