name: Tag and Create Release

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      github-runner:
        required: true
        type: string
    secrets:
      CICD_TOKEN:
        required: false

jobs:
  tag_release:
    runs-on: ${{ inputs.github-runner }} 
    environment: ${{ inputs.environment }}
    env:
      ENVIRONMENT: ${{ inputs.environment }}
      CICD_TOKEN: ${{ secrets.CICD_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Fetch all history and tags

      - name: Read Release version from release manifest
        run: echo "RELEASE=$(jq -r '.version' "releases/release-manifest.$ENVIRONMENT.json")" >> $GITHUB_ENV

      - name: Tag Release
        run: scripts/tag-release.sh 

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          token: ${{ secrets.CICD_TOKEN }}
          tag_name: v${{ env.RELEASE }}
          name: "Release ${{ env.RELEASE }} for ${{ env.ENVIRONMENT }} environment"
