name: Release 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      action:
        required: true
        type: string
      github-runner:
        required: true
        type: string
      release:
        required: true 
        type: string
      release_manifest:
        required: true 
        type: string
    secrets:
      GOOGLE_CREDENTIALS_B64:
        required: false 
      CICD_TOKEN:
        required: true

jobs:
  release:
    runs-on: ${{ inputs.github-runner }}
    environment: ${{ inputs.environment }}
    env:
      CICD_TOKEN: ${{ secrets.CICD_TOKEN }}
      ACTION: ${{ inputs.action }} 
      ENVIRONMENT: ${{ inputs.environment }}
      RELEASE_MANIFEST: ${{ inputs.release_manifest }}
      RELEASE: ${{ inputs.release }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        with:
          repository: aka-org/release_manager
          ref: v1.0.1

      - id: 'auth'
        if: inputs.action == 'PREPARE'
        uses: 'google-github-actions/auth@v2.0.0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_B64 }}'

      - name: 'Set up Cloud SDK'
        if: inputs.action == 'PREPARE'
        uses: 'google-github-actions/setup-gcloud@v2.0.0'

      - name: Run release manager 
        run: ./infra.sh
          
      - name: Create Release
        if: inputs.action == 'ROLLOUT'
        uses: softprops/action-gh-release@v2.2.2
        with:
          token: ${{ secrets.CICD_TOKEN }}
          tag_name: v${{ env.RELEASE }}
          name: "v${{ env.RELEASE }}"
