name: Tag and Create Release

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      github-runner:
        required: true
        type: string
    secrets:
      CICD_TOKEN:
        required: false

jobs:
  tag_release:
    runs-on: ${{ inputs.github-runner }} 
    environment: ${{ inputs.environment }}
    env:
      ENVIRONMENT: ${{ inputs.environment }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Fetch all history and tags

      - name: Tag Release
        run: |
          echo "RELEASE=$(jq -r '.version' "releases/release-manifest.${{ env.ENVIRONMENT  }}.json")" >> $GITHUB_ENV

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.CICD_TOKEN }}@github.com/${{ github.repository }}

          git tag -a "v${{ env.RELEASE }}" -m "Release ${{ env.RELEASE }} for ${{ env.ENVIRONMENT }} environment"
          git push origin "v${{ env.RELEASE }}"

      - name: Create Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: v${{ env.RELEASE }}
          name: "Release ${{ env.RELEASE }} for ${{ env.ENVIRONMENT }} environment"
