name: Rollout Release 
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  filter_envs:
    if: > 
      github.event.pull_request.merged == true
      && startsWith(github.event.pull_request.head.ref, 'releases/prep')
    runs-on: ubuntu-22.04
    outputs:
      testing: ${{ steps.filter.outputs.testing }}
      prod: ${{ steps.filter.outputs.prod }}
      testing_release: ${{ steps.releases.outputs.testing }}
      prod_release: ${{ steps.releases.outputs.prod }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Filter envs with changes
        id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            testing:
              - 'releases/release-manifest.testing.json'
            prod:
              - 'releases/release-manifest.prod.json'

      - name: Get release versions from release manifests
        id: releases
        run: |
          testing=$(jq -r '.version' "releases/release-manifest.testing.json")
          echo "testing=$testing" >> "$GITHUB_OUTPUT"
          prod=$(jq -r '.version' "releases/release-manifest.prod.json")
          echo "prod=$prod" >> "$GITHUB_OUTPUT"

  testing:
    needs: filter_envs
    if: needs.filter_envs.outputs.testing == 'true'
    uses: ./.github/workflows/release.yml
    with:
      action: ROLLOUT 
      environment: testing
      github-runner: ubuntu-22.04
      release_manifest: releases/release-manifest.testing.json
      release: ${{ needs.filter_env.outputs.testing_release }}
    secrets:
      CICD_TOKEN: ${{ secrets.CICD_TOKEN }}
