name: Rollout Release 
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  filter_envs:
    if: > 
      github.event.pull_request.merged == true
      && startsWith(github.event.pull_request.head.ref, 'releases/prep')
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Filter envs with changes
        id: filter_envs
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            testing:
              - 'releases/release-manifest.testing.json'
            prod:
              - 'releases/release-manifest.prod.json'

      - name: Build matrix based on changed envs
        id: set-matrix
        run: |
          MATRIX=()
          if [[ "${{ steps.filter-envs.outputs.testing }}" == "true" ]]; then
            MATRIX+=('{"env":"testing")
          fi
          if [[ "${{ steps.filter-envs.outputs.prod }}" == "true" ]]; then
            MATRIX+=('{"env":"prod")
          fi
          echo "matrix=$(jq -n --argjson m "[${MATRIX[*]}]" '$m')" >> $GITHUB_OUTPUT

  rollout_release:
    needs: filter_envs
    if: needs.filter_envs.outputs.matrix != '[]' 
    runs-on: ubuntu-22.04
    env:
      CICD_TOKEN: ${{ secrets.CICD_TOKEN }}
      ENVIRONMENT: ${{ matrix.env }}
      RELEASE_MANIFEST: releases/release-manifest.${{ matrix.env }}.json
      ACTION: ROLLOUT 

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Set RELEASE environment variable
        run: echo "RELEASE=$(jq -r '.version' $RELEASE_MANIFEST)" >> $GITHUB_ENV

      - name: Promote components, deprovision components and add release tag
        run: scripts/release-manager.sh
          
      - name: Create Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          token: ${{ secrets.CICD_TOKEN }}
          tag_name: v${{ env.RELEASE }}
          name: "v${{ env.RELEASE }}"
