name: Sync Infra 

on:
  push:
    tags:
      - '**'
    branches:
      - 'feature/**'
      - 'releases/**'
    paths:
      - 'terraform/**'

jobs:
  filter_envs:
    runs-on: ubuntu-22.04
    outputs:
      testing: ${{ steps.filter.outputs.testing }}
      prod: ${{ steps.filter.outputs.prod }}
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Filter envs with changes
        id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            testing:
              - 'terraform/**/testing/**'
              - 'releases/release-manifest.testing.json'
            prod:
              - 'terraform/**/prod/**'
              - 'releases/release-manifest.prod.json'

  testing:
    needs: filter_envs
    if: needs.filter_envs.outputs.testing == 'true' 
    uses: ./.github/workflows/provision-components.yml
    with:
      project: gcloud-infra-testing-aab1735b
      environment: testing 
      terraform-version: 1.11.4
      github-runner: ubuntu-22.04
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
      BILLING_ACCOUNT_ID: ${{ secrets.BILLING_ACCOUNT_ID }}
