name: Terraform Apply

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working-directory:
        required: true
        type: string
      tf-state-prefix:
        required: true
        type: string

jobs:
  apply:
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-22.04   
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    env:
      TF_VAR_billing_account_id: ${{ secrets.BILLING_ACCOUNT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: "${{ inputs.terraform-version }}"

      - name: Authenticate to GCP
        uses: google-github-actions/auth@2.1.10
        with:
          token_format: "id_token"
          workload_identity_provider: ${{ env.WIF_PROVIDER }} 
          service_account: ${{ env.WIF_SA }}

      - name: Terraform Init
        run: terraform init -backend-config=\"prefix=${{ inputs.tf-state-prefix }}\"

      - name: Check Terraform Formatting
        run: terraform fmt -check -recursive

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan 

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
