name: Apply Terraform

on:
  pull_request:
    branches: [main]
    paths:
      - 'environments/testing/**'
      - 'modules/**'
      - '.github/workflows/testing.yml'
      - '.github/workflows/terraform-apply.yml'  
  workflow_dispatch:

jobs:
  apply:
    uses: ./.github/workflows/terraform-apply.yml
    if: github.event_name == 'pull_request'
    with:
      environment: testing
      working-directory: environments/testing
      terraform-version: 1.11.3
      github-runner: ubuntu-22.04
