name: Provision Testing Environment

on:
  pull_request:
    branches: [main]

jobs:
  filter:
    runs-on: ubuntu-22.04
    outputs:
      project: ${{ steps.filter.outputs.project }}
      network: ${{ steps.filter.outputs.network }}
      k8s_blue: ${{ steps.filter.outputs.k8s_blue }}
      k8s_green: ${{ steps.filter.outputs.k8s_green }}
      packer: ${{ steps.filter.outputs.packer }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            project:
              - 'terraform/env/testing/project/**'
            network:
              - 'terraform/env/testing/network/**'
            k8s_blue:
              - 'terraform/env/testing/k8s_blue/**'
            k8s_green:
              - 'terraform/env/testing/k8s_green/**'
            packer:
              - 'packer/**'

  packer:
    needs: filter
    if: needs.filter.outputs.packer == 'true' 
    uses: ./.github/workflows/filter-images.yml
    with:
      environment: testing
      project: gloud-infra-testing-aan1735b  
      github-runner: ubuntu-22.04
      packer-version: 1.12.0 
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
  project:
    needs: filter
    if: needs.filter.outputs.project == 'true' 
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: testing
      working-directory: terraform/env/testing/project
      terraform-version: 1.11.4
      github-runner: ubuntu-22.04
      tf-state: gcloud-infra-testing-aab1735b-project-tf-state
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
      BILLING_ACCOUNT_ID: ${{ secrets.BILLING_ACCOUNT_ID }}
  network:
    needs: [filter, project]
    if: needs.filter.outputs.network == 'true' 
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: testing
      working-directory: terraform/env/testing/network
      terraform-version: 1.11.4
      github-runner: ubuntu-22.04
      tf-state: gcloud-infra-testing-aab1735b-network-tf-state
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
  k8s_blue:
    needs: [filter, project, network]
    if: needs.filter.outputs.k8s_blue == 'true' 
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: testing
      working-directory: terraform/env/testing/k8s_blue
      terraform-version: 1.11.4
      github-runner: ubuntu-22.04
      tf-state: gcloud-infra-testing-aab1735b-k8s-blue-tf-state
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
  k8s_green:
    needs: [filter, project, network]
    if: needs.filter.outputs.k8s_green == 'true' 
    uses: ./.github/workflows/terraform-apply.yml
    with:
      environment: testing
      working-directory: terraform/env/testing/k8s_green
      terraform-version: 1.11.4
      github-runner: ubuntu-22.04
      tf-state: gcloud-infra-testing-aab1735b-k8s-green-tf-state
    secrets:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
