name: Trigger Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      github-runner:
        required: true
        type: string
      repo:
        required: true
        type: string
      workflow_file:
        required: true
        type: string
    secrets:
      GITHUB_REPO_TOKEN:
        required: true

jobs:
  trigger:
    runs-on: ${{ inputs.github-runner }}
    environment: ${{ inputs.environment }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_REPO_TOKEN }}
      REPO: ${{ inputs.repo }}
      WORKFLOW_FILE: ${{ inputs.workflow_file }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Trigger workflow in Repo  
        run: ./scripts/trigger-github-workflow.sh
