name: Update Terraform tfvars 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      github-runner:
        required: true
        type: string
      project:
        required: true
        type: string
    secrets:
      GOOGLE_CREDENTIALS_B64:
        required: true
      CICD_TOKEN:
        required: false

jobs:
  update_tfvars:
    runs-on: ${{ inputs.github-runner }}
    environment: ${{ inputs.environment }}
    env:
      GOOGLE_CREDENTIALS_B64: ${{ secrets.GOOGLE_CREDENTIALS_B64 }}
      CICD_TOKEN: ${{ secrets.CICD_TOKEN }}
      ENVIRONMENT: ${{ inputs.environment }}
      PROJECT: ${{ inputs.project }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2.0.0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_B64 }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2.0.0'

      - name: Update terraform tfvars 
        run: scripts/update-terraform-tfvars.sh
